In [2]:
#Importing tensorflow and numpy
import tensorflow as tf
import numpy as np
import sklearn 
import tensorflow.python.platform
from tensorflow.python.platform import gfile
import os
import re

In [3]:
#initializing the imagenet directory and training images directory
model_dir = "imagenet"
attribute_training_images = "ClothingAttributeDataset/images/"

In [4]:
#Getting the list of training images names
training_images = [attribute_training_images+f for f in os.listdir(attribute_training_images) if re.search('jpg|JPG', f)]

In [5]:
#This function is from classify_image.py which creates graph from saved GraphDef file and returns a saver
def create_graph():
  """Creates a graph from saved GraphDef file and returns a saver."""
  # Creates graph from saved graph_def.pb.
  with tf.gfile.FastGFile(os.path.join(
      model_dir, 'classify_image_graph_def.pb'), 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    _ = tf.import_graph_def(graph_def, name='')

In [6]:
#Function to generate bottleneck values from classifyimage.py
def get_bottleneck_values(images):  # modifying name of function
  """Runs inference on an image.

  Args:
    image: Image file name.

  Returns:
    Nothing
  """
  # Creates graph from saved GraphDef.
  create_graph()
  feature_vector_size = 2048 # pool_3:0 contains a float description vector of size 2048  
  with tf.Session() as sess:
    # Some useful tensors:
    # 'softmax:0': A tensor containing the normalized prediction across
    #   1000 labels.
    # 'pool_3:0': A tensor containing the next-to-last layer containing 2048
    #   float description of the image.
    # 'DecodeJpeg/contents:0': A tensor containing a string providing JPEG
    #   encoding of the image.
    # Runs the softmax tensor by feeding the image_data as input to the graph.
    bottleneck_tensor = sess.graph.get_tensor_by_name('pool_3:0') #changing from softmax:0 to pool_3:0
    feature_vectors = np.empty([len(images),2048])
    image_names = []
    for i,image in enumerate(images): # Iterating through images 
        image_data = tf.gfile.FastGFile(image, 'rb').read()
        feature_vector = sess.run(bottleneck_tensor,
                           {'DecodeJpeg/contents:0': image_data})
        feature_vector = np.squeeze(feature_vector)
        image_names.append(image)
        feature_vectors[i,:] = feature_vector 
        if(i % 10 == 0): #Print out just to see the function is processing 
            print("Processing image %d  %s"%(i,image))
    return feature_vectors,image_names

In [37]:
attribute_features,image = get_bottleneck_values(training_images)

Processing image 0  ClothingAttributeDataset/images/000848.jpg
Processing image 10  ClothingAttributeDataset/images/001335.jpg
Processing image 20  ClothingAttributeDataset/images/000962.jpg
Processing image 30  ClothingAttributeDataset/images/000127.jpg
Processing image 40  ClothingAttributeDataset/images/000828.jpg
Processing image 50  ClothingAttributeDataset/images/000939.jpg
Processing image 60  ClothingAttributeDataset/images/000549.jpg
Processing image 70  ClothingAttributeDataset/images/001625.jpg
Processing image 80  ClothingAttributeDataset/images/001157.jpg
Processing image 90  ClothingAttributeDataset/images/001500.jpg
Processing image 100  ClothingAttributeDataset/images/001686.jpg
Processing image 110  ClothingAttributeDataset/images/001195.jpg
Processing image 120  ClothingAttributeDataset/images/001638.jpg
Processing image 130  ClothingAttributeDataset/images/000545.jpg
Processing image 140  ClothingAttributeDataset/images/001411.jpg
Processing image 150  ClothingAttrib

In [6]:
import pickle
attribute_features = pickle.load(open('attribute_features', 'rb'))
image_names = pickle.load(open('image_names','rb'))

In [7]:
attribute_features[1820]

array([ 0.80490333,  0.15159373,  0.69034594, ...,  0.22270462,
        0.22687191,  0.11126333])

In [8]:
full_sleeve = pickle.load(open('full_sleve','rb'))
half_sleeve = pickle.load(open('half_sleeve','rb'))
no_sleeve = pickle.load(open('sleeve_less','rb'))

In [9]:
def finnum(df):
     for i,r in enumerate(le):
             if re.search(df,r):
                     return i


In [10]:
train_features = np.concatenate((full_sleeve, half_sleeve, no_sleeve),axis = 0)

In [11]:
shape_full = full_sleeve.shape
shape_half = half_sleeve.shape
shape_no = no_sleeve.shape

In [12]:
feature_vectors_sorted = np.empty([len(training_images),2048])
image_name_sorted = []

In [13]:
lu = []
lu.append(le[2])

NameError: name 'le' is not defined

In [14]:
lu

[]

In [15]:
def sort():
    k = 0
    for i in range(1,1857):
        num_string = str(i)
        l = len(num_string)
        num_string = ("0" * (6-l)) + num_string
        for index, name in enumerate(image_names):
            if re.search(num_string, name):
                feature_vectors_sorted[k,:] = attribute_features[index,:]
                image_name_sorted.append(image_names[index])
                k = k+1

In [16]:
if re.search("000024",image_names[1827]):
    jk = 1
else:
    jk = 2

In [17]:
jk

2

In [18]:
sort()

In [16]:
import pickle
feature_vectors_sorted = pickle.load(open('feature_vectors_sorted','rb'))
image_name_sorted = pickle.load(open('image_names_sorted','rb'))

In [7]:
len(image_name_sorted)

1856

In [8]:
image_name_sorted[25]

'ClothingAttributeDataset/images/000026.jpg'

In [10]:
feature_vectors_sorted[25:,]

array([[ 0.80490333,  0.15159373,  0.69034594, ...,  0.22270462,
         0.22687191,  0.11126333],
       [ 0.16255185,  0.15097639,  0.51625961, ...,  0.10021258,
         0.22002977,  0.97462893],
       [ 0.44787368,  0.29137346,  0.32642001, ...,  0.52751476,
         0.26356316,  0.89175224],
       ..., 
       [ 0.01131292,  0.20026733,  0.03646646, ...,  0.2837038 ,
         0.95965981,  0.39441887],
       [ 0.39169762,  0.02050794,  0.35033047, ...,  0.00184   ,
         0.42654708,  0.09642667],
       [ 0.26268733,  0.03748782,  0.34740242, ...,  0.09256094,
         1.7063657 ,  0.10101566]])

In [23]:
im = []
im.append(image_name_sorted[25])

In [31]:
h,j = get_bottleneck_values(im)

Processing image 0  ClothingAttributeDataset/images/000026.jpg


In [32]:
h

array([[ 0.80490333,  0.15159373,  0.69034594, ...,  0.22270462,
         0.22687191,  0.11126333]])

In [33]:
j

['ClothingAttributeDataset/images/000026.jpg']

In [7]:
import pickle
images_names_sorted = pickle.load(open("image_names_sorted",'rb'))
feature_vector_sorted = pickle.load(open("feature_vectors_sorted",'rb'))

In [8]:
import pandas as pd
sleeve_len = pd.read_csv('ClothingAttributeDataset/labels/sleeve_length.csv',header=None)
pattern_stripe = pd.read_csv('ClothingAttributeDataset/labels/pattern_stripe.csv',header=None)
collar = pd.read_csv('ClothingAttributeDataset/labels/collar.csv',header=None)
pattern_graphics = pd.read_csv('ClothingAttributeDataset/labels/pattern_graphics.csv',header=None)
white_color = pd.read_csv('ClothingAttributeDataset/labels/white.csv',header=None)
yellow_color = pd.read_csv('ClothingAttributeDataset/labels/yellow.csv',header=None)
skin_exposure = pd.read_csv('ClothingAttributeDataset/labels/skin_exposure.csv',header=None)

In [11]:
sleeve_len.fillna(0, inplace=True)
pattern_stripe.fillna(0, inplace=True)
collar.fillna(0, inplace=True)
pattern_graphics.fillna(0, inplace=True)
white_color.fillna(0, inplace=True)
yellow_color.fillna(0, inplace=True)
skin_exposure.fillna(0, inplace=True)

In [34]:
sleeve_len

0
0     3.0
1     3.0
2     3.0
3     3.0
4     1.0
5     3.0
6     3.0
7     3.0
8     3.0
9     3.0
10    1.0
11    3.0
12    3.0
13    3.0
14    3.0
15    3.0
16    2.0
17    3.0
18    3.0
19    3.0
20    3.0
21    3.0
22    1.0
23    3.0
24    3.0
25    3.0
26    3.0
27    3.0
28    3.0
29    2.0
...   ...
1826  0.0
1827  3.0
1828  2.0
1829  2.0
1830  2.0
1831  1.0
1832  1.0
1833  3.0
1834  1.0
1835  3.0
1836  3.0
1837  3.0
1838  2.0
1839  1.0
1840  1.0
1841  2.0
1842  3.0
1843  3.0
1844  2.0
1845  0.0
1846  3.0
1847  2.0
1848  2.0
1849  3.0
1850  1.0
1851  3.0
1852  1.0
1853  3.0
1854  3.0
1855  1.0

[1856 rows x 1 columns]

In [35]:
sleeve_ar = sleev.as_matrix()

In [37]:
np.unique(sleev_len)

array([ 0.,  1.,  2.,  3.])

In [30]:
sleeve_np = np.empty([1857,1])
sleeve_np = sleeve_ar

In [31]:
sleeve_np.shape

(1856, 1)

In [32]:
feature_vector_sorted.shape

(1856, 2048)

In [9]:
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras import optimizers

Using TensorFlow backend.


In [39]:
from sklearn.model_selection import train_test_split

In [20]:
#train_sleeve, test_sleeve, train_res_sleeve, test_res_sleeve = train_test_split(feature_vector_sorted,sleeve_np)

In [10]:
from keras.utils.np_utils import to_categorical
#categorical_labels_train = to_categorical(train_res_sleeve, nb_classes=None)
#categorical_labels_test = to_categorical(test_res_sleeve, nb_classes=None)
#train_categorical = to_categorical(sleeve_ar,nb_classes=None)
#train_categorical
#import scipy
#a=np.delete(train_categorical,0,axis=1)


In [36]:
np.sum(a,axis=0)

array([  188.,   323.,  1270.,    75.])

In [37]:
nn = Sequential()
nn.add(Dense(256,input_dim=2048,activation = 'relu'))
nn.add(Dropout(0.5))
nn.add(Dense(output_dim=4, activation='softmax'))
nn.compile(optimizer='adadelta', loss='categorical_crossentropy',metrics=['accuracy'])

In [11]:
def getFullyConnectedLayer(no_of_categories):
    nn = Sequential()
    nn.add(Dense(256,input_dim=2048,activation = 'relu'))
    nn.add(Dropout(0.5))
    nn.add(Dense(output_dim=no_of_categories, activation='softmax'))
    nn.compile(optimizer='adadelta', loss='categorical_crossentropy',metrics=['accuracy'])
    return nn

In [12]:
def trainFullyConnectedLayer(neural_network,X,Y):
    nb_epoch=80
    Y_Categorical = to_categorical(Y,nb_classes=None)
    neural_network.fit(X, Y_Categorical,
              nb_epoch=nb_epoch, batch_size=32)
    return neural_network

In [78]:
sleeve_len_nn = getFullyConnectedLayer(4)
sleeve_len_nn = trainFullyConnectedLayer(sleeve_len_nn,feature_vectors_sorted,sleeve_len)
sleeve_len_nn.save_weights('sleeve_weights.h5')

Epoch 1/80
1856/1856 [==============================] - 1s - loss: 0.8068 - acc: 0.7236      

In [79]:
white_color_nn = getFullyConnectedLayer(3)
white_color_nn = trainFullyConnectedLayer(white_color_nn,feature_vectors_sorted,white_color)
white_clor_nn.save_weights('white_col_weights.h5')

Epoch 1/80
1856/1856 [==============================] - 1s - loss: 0.8596 - acc: 0.6557      

In [80]:
yellow_color_nn = getFullyConnectedLayer(3)
yellow_color_nn = trainFullyConnectedLayer(yellow_color_nn,feature_vectors_sorted,yellow_color)
yellow_color_nn.save_weights('yellow_color.h5')

Epoch 1/80
1856/1856 [==============================] - 1s - loss: 0.4727 - acc: 0.8885      

In [81]:
pattern_stripe_nn = getFullyConnectedLayer(3)
pattern_stripe_nn = trainFullyConnectedLayer(pattern_stripe_nn,feature_vectors_sorted,pattern_stripe)
pattern_stripe_nn.save_weights('pattern_stripe_weights.h5')

Epoch 1/80
1856/1856 [==============================] - 2s - loss: 0.6555 - acc: 0.7990      

In [82]:
pattern_graphics_nn = getFullyConnectedLayer(3)
pattern_graphics_nn = trainFullyConnectedLayer(pattern_graphics_nn,feature_vectors_sorted,pattern_graphics)
pattern_graphics_nn.save_weights('pattern_graphics_weight.nn')

Epoch 1/80
1856/1856 [==============================] - 2s - loss: 0.3557 - acc: 0.9122      

In [83]:
collor_nn = getFullyConnectedLayer(3)
collor_nn = trainFullyConnectedLayer(collor_nn,feature_vectors_sorted,collar)
collor_nn.save_weights('collor_weights.h5')

Epoch 1/80
1856/1856 [==============================] - 1s - loss: 0.9478 - acc: 0.5819      

In [84]:
skin_exp_nn = getFullyConnectedLayer(3)
skin_exp_nn = trainFullyConnectedLayer(skin_exp_nn,feature_vectors_sorted,skin_exposure)
skin_exp_nn.save_weights('skin_exp_weights.h5')

Epoch 1/80
1856/1856 [==============================] - 1s - loss: 0.6017 - acc: 0.7963      

In [38]:
nb_epoch=100
nn.fit(feature_vector_sorted, a,
          nb_epoch=nb_epoch, batch_size=32)
          #validation_data=(test_sleeve, test_res_sleeve))

Epoch 1/100
1856/1856 [==============================] - 1s - loss: 0.8086 - acc: 0.7263      

In [39]:
nn.evaluate(test_sleeve, test_res_sleeve)

NameError: name 'test_sleeve' is not defined

In [33]:
val = ['test.jpg']
#val.append(image_name_sorted[0])
val_feat,j = get_bottleneck_values(val[0:1])

Processing image 0  test.jpg


In [86]:
val_feat

array([[ 0.16566545,  0.11264835,  0.12659082, ...,  0.05062337,
         0.67032236,  0.15982868]])

In [81]:
a = feature_vector_sorted[42:43,:]
predictions = nn.predict(a)
label = ["no","half","full","not sure"]

In [82]:
top_k = predictions[0].argsort()[-len(predictions[0]):][::-1]
    
for node_id in top_k:
    human_string = label[node_id]
    score = predictions[0][node_id]
    print('%s (score = %.5f)' % (human_string, score))

not sure (score = 0.99635)
full (score = 0.00177)
half (score = 0.00153)
no (score = 0.00035)


In [76]:
predictions[0].argsort()[-len(predictions[0]):][::-1]

array([0, 1, 3, 2])

In [13]:
def predictAttributes(image):
    sleve_len_nn = getFullyConnectedLayer(4);
    sleve_len_nn.load_weights("sleeve_weights.h5")
    sleeve_prediction = sleve_len_nn.predict(image)
    sleeve_labels = ["Not sure, need to get some brain tweaking","No Sleeves","Half Sleeves", "Full sleeves"]
    printPredictions(sleeve_prediction, sleeve_labels)
    
    white_color_nn = getFullyConnectedLayer(3)
    #white_color_nn = trainFullyConnectedLayer(white_color_nn,feature_vectors_sorted,white_color)
    white_color_nn.load_weights('white_col_weights.h5')
    white_prediction = white_color_nn.predict(image)
    white_color_labels = ["Pretty confusing to tell if its white Sorry","Not white", "White"]
    printPredictions(white_prediction, white_color_labels)
    
    pattern_stripe_nn = getFullyConnectedLayer(3)
    #pattern_stripe_nn = trainFullyConnectedLayer(pattern_stripe_nn,feature_vectors_sorted,pattern_stripe)
    pattern_stripe_nn.load_weights('pattern_stripe_weights.h5')
    pattern_strip_prediction = pattern_stripe_nn.predict(image)
    pattern_strip_labels = ["Not sure buddy", "Striped", "No Stripes"]
    printPredictions(pattern_strip_prediction, pattern_strip_labels)
    
    pattern_graphics_nn = getFullyConnectedLayer(3)
    #pattern_graphics_nn = trainFullyConnectedLayer(pattern_graphics_nn,feature_vectors_sorted,pattern_graphics)
    pattern_graphics_nn.load_weights('pattern_graphics_weight.nn')
    pattern_graphics_prediction = pattern_graphics_nn.predict(image)
    pattern_graphics_labels = ["Not sure buddy", "No Graphics", "Ohhh Graphics"]
    printPredictions(pattern_graphics_prediction, pattern_graphics_labels)
    
    yellow_color_nn = getFullyConnectedLayer(3)
    #yellow_color_nn = trainFullyConnectedLayer(yellow_color_nn,feature_vectors_sorted,yellow_color)
    yellow_color_nn.load_weights('yellow_color.h5')
    yellow_prediction = yellow_color_nn.predict(image)
    yellow_color_labels = ["Pretty confusing to tell if its yellow Sorry","Not yellow", "Yellow yellow dirty fellow"]
    printPredictions(yellow_prediction, yellow_color_labels)
    
    skin_exp_nn = getFullyConnectedLayer(3)
    #skin_exp_nn = trainFullyConnectedLayer(skin_exp_nn,feature_vectors_sorted,skin_exposure)
    skin_exp_nn.load_weights('skin_exp_weights.h5')
    skin_ex_prediction = white_color_nn.predict(image)
    skin_ex_labels = ["I cant tell","You are covered", "Might get tanned"]
    printPredictions(skin_ex_prediction, skin_ex_labels)
    
    collor_nn = getFullyConnectedLayer(3)
    #collor_nn = trainFullyConnectedLayer(collor_nn,feature_vectors_sorted,collar)
    collor_nn.load_weights('collor_weights.h5')
    collar_prediction = white_color_nn.predict(image)
    collar_labels = ["I need more data boy","No Collar", "Collar"]
    printPredictions(collar_prediction, collar_labels)

In [14]:
def printPredictions(prediction, labels):
    top_k = prediction[0].argsort()[-len(prediction[0]):][::-1]
    
    for node_id in top_k:
        human_string = labels[node_id]
        score = prediction[0][node_id]
        print('%s (score = %.5f)' % (human_string, score))
    print('\n')

In [21]:
#a = val_feat
a = feature_vectors_sorted[0:1,:]
predictAttributes(a)

Full sleeves (score = 1.00000)
Not sure, need to get some brain tweaking (score = 0.00000)
Half Sleeves (score = 0.00000)
No Sleeves (score = 0.00000)


Not white (score = 0.72825)
White (score = 0.17881)
Pretty confusing to tell if its white Sorry (score = 0.09294)


Not sure buddy (score = 0.99684)
No Stripes (score = 0.00304)
Striped (score = 0.00012)


No Graphics (score = 1.00000)
Not sure buddy (score = 0.00000)
Ohhh Graphics (score = 0.00000)


Not yellow (score = 0.98563)
Pretty confusing to tell if its yellow Sorry (score = 0.01436)
Yellow yellow dirty fellow (score = 0.00001)


You are covered (score = 0.72825)
Might get tanned (score = 0.17881)
I cant tell (score = 0.09294)


No Collar (score = 0.72825)
Collar (score = 0.17881)
I need more data boy (score = 0.09294)


